# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Telephone', '0001_initial'),
        ('Personne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoirTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumeroTelephone', models.ManyToManyField(to='Telephone.Telephone')),
                ('idProprietaireTelephone', models.ManyToManyField(to='Personne.Personne')),
            ],
        ),
    ]
