# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionDuTraitement', models.TextField()),
                ('idOrdonnanceTr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ordonnance.ordonnance')),
            ],
        ),
    ]
