# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeMedecin',
            fields=[
                ('idGradeMedecin', models.AutoField(primary_key=True, serialize=False)),
                ('nomDuGrade', models.CharField(max_length=20)),
                ('descriptionDuGrade', models.TextField(max_length=20)),
            ],
        ),
    ]
