# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('idAdresse', models.AutoField(primary_key=True, serialize=False)),
                ('nomPays', models.CharField(max_length=15)),
                ('nomVille', models.CharField(max_length=15)),
                ('nomQuartier', models.CharField(max_length=15)),
                ('Indication', models.CharField(max_length=15)),
            ],
        ),
    ]
