# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlageHoraire', '0001_initial'),
        ('Medecin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnePlageHoraireDuMedecin',
            fields=[
                ('idUnePlageHoraireDuMedecin', models.AutoField(primary_key=True, serialize=False)),
                ('HeureDebut', models.TimeField()),
                ('HeureFin', models.TimeField()),
                ('idMedecinPH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Medecin.medecin')),
                ('idPlageHoraireTotal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PlageHoraire.plagehoraire')),
            ],
        ),
    ]
