# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adresse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idPersonne', models.AutoField(primary_key=True, serialize=False)),
                ('nomPersonne', models.CharField(max_length=15, null=True)),
                ('prenomPersonne', models.CharField(max_length=15, null=True)),
                ('dateNaissancePersonne', models.DateField()),
                ('lieuDeNaissancePersonne', models.CharField(blank=True, max_length=20, null=True)),
                ('sexePersonne', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('emailPersonne', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephonePersonne', models.IntegerField(blank=True, null=True)),
                ('adressePersonne', models.CharField(blank=True, max_length=20, null=True)),
                ('statutPersonne', models.CharField(choices=[('A', 'Actif'), ('I', 'Inactif')], max_length=1)),
                ('AdressePersonne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adresse.adresse')),
            ],
        ),
    ]
