# Generated by Django 4.0 on 2021-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personne', '0002_remove_personne_adressepersonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='statutPersonne',
            field=models.CharField(choices=[('A', 'Actif'), ('I', 'Inactif')], default='A', max_length=1),
        ),
    ]
