# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GradeMedecin', '0001_initial'),
        ('ServiceHopital', '0001_initial'),
        ('Personne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Personne.personne')),
                ('gradeMedecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GradeMedecin.grademedecin')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServiceHopital.servicehopital')),
            ],
            bases=('Personne.personne',),
        ),
    ]
